export * from './v1/admin.controller'
export * from './v1/image.controller'
export * from './v1/news-events-category.controller'
export * from './v1/news-events.controller'
export * from './v1/policy.controller'
export * from './v1/role.controller'
export * from './v1/auth.controller'
export * from './v1/dashboard.controller'
